name: OpenAI API Example

# Workflow triggers
on:
  # Run on a schedule (daily at 9:00 AM UTC)
  schedule:
    - cron: '0 9 * * *'
  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  run-openai-script:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Install dependencies
      - name: Install OpenAI package
        run: |
          python -m pip install --upgrade pip
          pip install openai
      
      # Run the OpenAI example script with secret injected
      - name: Run OpenAI example script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python openai_example.py
